### PR TITLE
Darkmode fixes

### LINKED ISSUE #19: Dark mode sidebar labels
While in dark mode, the currently selected label is very hard to read.

image

### PR DESCRIPTION
**Pull request by Adamlip1334**
Closes #19 changed sidebar background so sidebar so sidebar item is readable. Also added darkmode support to the homepage. 
image

### CODE REVIEW

**Comment by shuaimu** [comment]
conflicts

**Review by andrewctam — CHANGES_REQUESTED** [review]
I think the selected text and icon should be darker for better contrast, and other labels should be brighter

**Comment by Adamlip1334** [comment]
fixed merge conflicts, will look into making changes suggested by andrew tomorrow

**Comment by Adamlip1334** [comment]
@andrewctam any feedback on the new sidebar

**Review by andrewctam — APPROVED** [review]
LGTM

**Pull request closed without merging**
